# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
      - README.md
      - .gitignore
      - .gitpod.yml
      - LICENSE    
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
      - README.md
      - .gitignore
      - .gitpod.yml
      - LICENSE    

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        # cache: 'npm'
        path: checkout
    - name: npm install
      run: npm install
      working-directory: checkout
    - run: npm run build --if-present
      working-directory: checkout

    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        # cache: 'npm'
        path: node-api
    - name: npm install
      run: npm install
      working-directory: checkout
    - run: npm run build --if-present
      working-directory: checkout
